import type { Project } from './types';

export const projects: Project[] = [
  {
    id: '1',
    title: 'AI-Powered Telemedicine Platform',
    group: 'Health Innovators',
    theme: 'Health',
    summary: 'A platform using AI to diagnose common ailments remotely, reducing the need for in-person visits.',
    description: 'This project aims to develop a comprehensive telemedicine platform that leverages machine learning algorithms to assist in preliminary diagnoses. It features video conferencing, a symptom checker chatbot, and secure patient data management. The goal is to improve healthcare accessibility in remote areas.',
    imageUrl: 'https://picsum.photos/600/400',
    imageHint: 'medical technology',
    continuationRequirements: 'Looking for a team with strong AI/ML and full-stack development skills to enhance diagnostic accuracy and expand the feature set.',
    contact: 'health.innovators@example.com',
    proposalUrl: '/proposal-placeholder.pdf',
  },
  {
    id: '2',
    title: 'Smart Waste Sorting System',
    group: 'Eco Warriors',
    theme: 'Waste Management',
    summary: 'An automated system using computer vision to sort recyclable materials, improving efficiency in waste processing.',
    description: 'Our system employs a conveyor belt, a camera, and a robotic arm controlled by a Raspberry Pi. A trained deep learning model identifies different types of waste (plastic, glass, paper) and directs the arm to sort them into appropriate bins. This reduces manual labor and contamination rates in recycling streams.',
    imageUrl: 'https://picsum.photos/600/400',
    imageHint: 'recycling factory',
    continuationRequirements: 'Team needed to miniaturize the prototype and improve the sorting speed. Knowledge of robotics and embedded systems is a plus.',
  },
  {
    id: '3',
    title: 'Urban Mobility Flow Analysis',
    group: 'City Planners',
    theme: 'Smart City',
    summary: 'A data-driven approach to analyze and predict traffic flow in urban centers to optimize public transport routes.',
    description: 'This project utilizes open-source traffic data and public transport schedules to build a predictive model for urban mobility. The dashboard visualizes traffic hotspots, predicts congestion, and suggests alternative routes for buses and emergency services. The core technology is a time-series analysis model built with Python and visualized using a web-based dashboard.',
    imageUrl: 'https://picsum.photos/600/400',
    imageHint: 'city traffic',
    contact: 'city.planners@example.com',
    proposalUrl: '/proposal-placeholder.pdf',
  },
  {
    id: '4',
    title: 'Eco-Friendly Last-Mile Delivery Drones',
    group: 'Green Transport Co.',
    theme: 'Environmentally Friendly Transportation',
    summary: 'Developing a network of autonomous drones for last-mile package delivery, reducing carbon emissions from delivery vans.',
    description: 'The project focuses on designing and testing energy-efficient delivery drones and a centralized control system for route planning and battery management. We have a working prototype that can carry a 2kg payload for up to 5km. Safety and regulatory compliance are key aspects of our research.',
    imageUrl: 'https://picsum.photos/600/400',
    imageHint: 'delivery drone',
    continuationRequirements: 'Seeking a team to work on battery efficiency, collision avoidance systems, and scaling the control software for a larger fleet.',
    contact: 'green.transport@example.com',
  },
    {
    id: '5',
    title: 'Wearable Health Monitor for Seniors',
    group: 'CareTech',
    theme: 'Health',
    summary: 'A discreet wearable device that monitors vital signs for elderly individuals and alerts caregivers of anomalies.',
    description: 'This device, designed as a simple bracelet, tracks heart rate, body temperature, and fall detection. Data is streamed in real-time to a mobile app for family members or caregivers. The focus is on user-friendliness, long battery life, and data privacy.',
    imageUrl: 'https://picsum.photos/600/400',
    imageHint: 'wearable technology',
    proposalUrl: '/proposal-placeholder.pdf',
  },
  {
    id: '6',
    title: 'Community Composting Initiative',
    group: 'Soil Savers',
    theme: 'Waste Management',
    summary: 'A web platform to connect households with local community gardens for composting organic waste.',
    description: 'The platform allows users to find nearby composting sites, track their contributions, and receive rewards in the form of fresh produce. It aims to reduce landfill waste and promote urban agriculture.',
    imageUrl: 'https://picsum.photos/600/400',
    imageHint: 'community garden',
    contact: 'soil.savers@example.com',
  },
];
